### ISSUE TITLE
CC-BY licence instead of Apache?

### ISSUE THREAD

**Issue by Remi-Gau** [brainhackorg/brainhack_cloud#3]
feels more appropriate for documentation, no?

- [x] change licence in the root of the repo
- [x] add licence mention in the footer rather than copy pasting it manually in all pages

**Comment by stebo85** [comment]
yes, good idea :)

**Comment by Remi-Gau** [comment]
updating the top message with things left to do

**Comment by Remi-Gau** [comment]
could not figure out how to control the footer easily yet

**Comment by SamGuay** [comment]
Happy to help. It seems the footer parses a couple of [i18n strings as seen in the theme repo](https://github.com/google/docsy/blob/7c865d0a2e0a7011dd92216e8c4013a1c37ffd7e/i18n/en.toml#L23-L28).

If you want to add stuff to the footer, it's easier to 1- copy the [footer.html partial](https://github.com/google/docsy/blob/7c865d0a2e0a7011dd92216e8c4013a1c37ffd7e/layouts/partials/footer.html#L19-L25) in `layouts/partial/footer.html` 2- modify or add stuff around the highlighted lines. With the copy in the layouts dir at the top of the [look-up hierarchy](https://gohugo.io/templates/lookup-order/#hugo-layouts-lookup-rules-with-theme), Hugo will build the footer with this page instead of the one in the themes/ dir (lower level in the hierarchy). 

If you don't want to hard code the license link in there, you can point at some params in the config file and we can pass them in the footer as they do with `{{ with .Site.Params.copyright }} {{ . }} {{ end }}`. 

Hopefully my tired brain interpreted what you meant correctly :sweat_smile:.

**Comment by Remi-Gau** [comment]
Your tired brain can still function.
I would like to avoid hard coding as much as possible and be able to change everything from the "main control room" (the config file).
I started playing with the toml to get something to display but only got half way there.

**Comment by SamGuay** [comment]
In the [config.toml](https://github.com/brainhackorg/brainhack_cloud/blob/f233c08b627fb8b7c0c728310c0aadd6982e2fb0/config.toml#L95-L98), did you add a new param, eg, `license_please = "All content is licensed under [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/)."`

Then in `footer.html` if you add this `{{ .Site.Params.license_please | markdownify }}`, it should appear anywhere.

(You may also want to copy over the `themes/docsy/i18n/en.toml` file to `i18n/en.toml` there to modify the strings you want.)

If you upload your branch, it would be easier for me to help instead of guessing what "got half way there" means. 

Also: can we convert all the toml to yaml please or at least in the main config? I might open an issue for this. Unless you prefer toml?

**Comment by stebo85** [comment]
Looks like it's all completed :) Great work everyone!!!
