### ISSUE TITLE
Could Shell Access Group is missing among the listed groups

### ISSUE THREAD

**Issue by complexbrains** [brainhackorg/brainhack_cloud#33]
Hi all. 

In the Policies doc under the Admins subpage of the Brainhack Cloud website, we have a mention of [Policy for Cloud Shell Acess](https://brainhack.org/brainhack_cloud/admins/policies/#:~:text=By%20default%2C%20a%20new%20user%20cannot%20open%20a%20Cloud%20Shell.%20To%20provide%20every%20user%20with%20this%20permission%2C%20we%20created%20a%20group%20called%20%E2%80%9Ccloudshell%2Daccess%E2%80%9D%20and%20we%20add%20every%20user%20to%20this%20group.%20The%20group%20then%20has%20a%20Policy%20that%20allows%20opening%20a%20cloud%20shell%3A%20allow%20group%20cloudshell%2Daccess%20to%20use%20cloud%2Dshell%20in%20tenancy) that gives rights to the user to access the Cloud shell. However such group is missing from the lists under Identity> Groups. 

I understand from the Oracle's [Cloud Shell](https://docs.oracle.com/en-us/iaas/Content/API/Concepts/cloudshellintro.htm) documents that  we do not need to create a specific group but when we create the group it is enough to give them the cloud shell access rights with 
```
allow group <GROUP-NAME> to use cloud-shell in tenancy
```
 is just enough. 

I wonder if this is the recommended way of doing for us too? If so I will append the document and delete the group indication instead will indicate to type that line of rule for the shell access policy.

**Comment by stebo85** [comment]
Dear @complexbrains 

Thank you for finding this bug in the documentation!

I renamed the group "cloudshell-access" to "projects" because I added more policies that we needed for the normal operation and I forgot to update the documentation - I fixed that now :)

the projects group contains the following policies right now:
![image](https://user-images.githubusercontent.com/4021595/164168605-2711144d-758e-4395-b891-bb2c29e80298.png)

you are right, that you could give every project group access to the cloudshell indiviudally, but doing it via a group gives us the flexibility of changing things later if we need to add more policies down the track :)

Thank you so much
Cheers
Steffen

**Comment by complexbrains** [comment]
Oh happy to hear! Indeed group policies make maintenance easier. I was just playing around to see if I can find a workaround.  Happy that it is resolved! Thank you so much 🤗
