### ISSUE TITLE
I would like to have access to some ressource

### ISSUE THREAD

**Issue by neurok8050** [brainhackorg/brainhack_cloud#53]
### Title

Easily accessible seed to voxel correlation and machine learning program in Python with high performance computer (HPC) and Docker.

### Is this a new project?

yes

### People involved

Claudéric DeRoy (Github user : neurok8050)

### Project Description

- What are you doing, for whom, and why?
I want to do the exercise from the HPC module. I also want to use the resource for my project.  

### Link to project repository/sources

https://github.com/brainhack-school2022/deroy_project

### What resources do you require?

HPC

**Comment by stebo85** [comment]
Dear @neurok8050 - we need an email address to create the account. Can you send this to the team on https://mattermost.brainhack.org/brainhack/channels/brainhack_cloud ?

**Comment by stebo85** [comment]
Dear @neurok8050 

the project is created under "seed_voxel_correlation". You have an email with the login details.

Kind regards
Steffen

**Comment by stebo85** [comment]
Dear @neurok8050,

I send you an email a few days ago to ask about your 3 HPC clusters you are running in your account and the underutilization of the cloud resources. Can you please respond to my email to let me know what is happening in your account - otherwise I have to shutdown the unused resources on the 5th of September.

Thank you
Steffen

**Comment by stebo85** [comment]
This project is now closed and all resources on the Oracle Cloud will be deleted within the next few days.
