### ISSUE TITLE
Freesurfer not working on NeuroDesk Trial (test server)

### ISSUE THREAD

**Issue by Andjelaaaa** [brainhackorg/brainhack_cloud#59]
Hi @stebo85 , 

I tried testing out the neurodesk to use the freesurfer tool via [the link you supplied](https://play.neurodesk.org/v2/gh/neurodesk/jupyter-neurodesktop-image/main?urlpath=neurodesktop) and there seems to be a license issue. Do I need to add another license file as indicated ? Here is the shown error message below 
`ERROR: FreeSurfer license file /usr/local/freesurfer/.license not found.
  If you are outside the NMR-Martinos Center,
  go to http://surfer.nmr.mgh.harvard.edu/registration.html to 
  get a valid license file (it's free).
  If you are inside the NMR-Martinos Center,
  make sure to source the standard environment.
  A path to an alternative license file can also be
  specified with the FS_LICENSE environmental variable. `
![image](https://user-images.githubusercontent.com/46799444/181370512-156a84db-1682-4b60-8c5a-2b72093cc42e.png)

**Comment by stebo85** [comment]
Dear @Andjelaaaa,

Yes, what you see is expected and the reason is that the Freesurfer Team does not allow a license file to be distributed and you need to apply for your own license if you want to use Freesurfer in Neurodesk.

This is described in the help when you open Freesurfer in Neurodesk:
<img width="608" alt="image" src="https://user-images.githubusercontent.com/4021595/181373948-701321b1-5db7-4b2b-a9fc-3cfa27d8e229.png">

For testing proposes you can do exactly what it says there:
```
echo "Steffen.Bollmann@cai.uq.edu.au
> 21029
>  *Cqyn12sqTCxo
>  FSxgcvGkNR59Y" >> ~/.license
 ```
then 
```
export FS_LICENSE=~/.license 
```

then you can run all Freesurfer tools as expected.

Of you course instead of using my freesurfer license you need to apply for your own.

Can you please let me know if this works for you? 
(make sure the license file doens't contain > in the beginning of the line!)

**Comment by Andjelaaaa** [comment]
Thank you for your response! By following these steps, it now indeed works!
